package com.oasis.infobyte;

import java.util.*;

class Game{
	public int randomNum;
	public int guess;
	public int noOfGuesses = 0;
	
	public void setNoOfGuesses(int noOfGuesses) {
		this.noOfGuesses = noOfGuesses;
	}
	
	public int getNoOfGuesses() {
		return noOfGuesses;
	}
	
	public boolean IsCorrectNumber(int randomNum, int guessNum) {
		noOfGuesses++;
	    
		if(guessNum == randomNum ) {
			System.out.println("Congratulations! you guessed the number, it is "+guessNum+"."); 
			System.out.println("You guessed in total "+noOfGuesses+ " attempts.");
		    	return true;
		}
		else if( guessNum < randomNum) {
			System.out.println("Guess higher number please!");
		}
		else if(guessNum > randomNum) {
			System.out.println("Guess lower number please!");
		}
		return false;
	}	 
}

public class NumberGuessingGame {
	
	public static void main(String[] args) {
		// TODO Auto-generated method stub
		Scanner sc = new Scanner(System.in);
		
		Random rand = new Random();
        	int randomNum = rand.nextInt(1,100);

        	System.out.println("The random number is successfully generated by the device.");
        	System.out.println("Now your turn to guess this number between 1 to 100...");
        
		Game game = new Game();
		
		boolean flag = false;
	    	while(!flag) {
	    		System.out.print("Guess the number: ");
			int guessNum = sc.nextInt();			
            		flag = game.IsCorrectNumber(randomNum, guessNum);
	    	} 
		
		if(sc!=null) {
			sc.close();
		}
	}
	
}
